### ISSUE TITLE
Error Evaluating Expression For Source Text: $F{detai}

### ISSUE THREAD

**Issue by nextaliakbar** [DJ-Raven/java-ireport-tutorial#2]
![Screenshot 2024-05-05 072305](https://github.com/DJ-Raven/java-ireport-tutorial/assets/136871867/e4c998a5-0f7a-4bd1-aa75-75a494316d04)
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[]' with class 'java.util.ArrayList' to class 'net.sf.jasperreports.engine.data.JRBeanCollectionDataSource' due to: org.codehaus.groovy.runtime.metaclass.MethodSelectionException: Could not find which method <init>() to invoke from this list:
  public net.sf.jasperreports.engine.data.JRBeanCollectionDataSource#<init>(java.util.Collection)
  public net.sf.jasperreports.engine.data.JRBeanCollectionDataSource#<init>(java.util.Collection, boolean);

Please Help me my friend, First i succes to make report with subtable, but when i want to make second report i have a problem like the problem above. Whereas i copy first design report.

**Comment by DJ-Raven** [comment]
This error when your field detail has no data or empty, I have fixed this by set `null` to ireport when filed is empty.

here code changed using `do while loop`:
https://github.com/DJ-Raven/java-ireport-tutorial/blob/5e558d5fd2dbdf350b73a8e4b25b4ecafb56632d/src/demo/sample2/Test.java#L109-L121

or you don't want to use `do while loop` you can use this:

``` java
fiels.add(new FieldReportInvoice(++no, invoice, date, time, totalQty, totalAmount, detail.isEmpty()?null:detail));
```

**Comment by nextaliakbar** [comment]
Thanks My Friend, I succes resolve the problem
